-- MySQL Script generated by MySQL Workbench
-- Tue 08 Oct 2019 08:52:57 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_logixla_crud
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_logixla_crud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_logixla_crud` ;
USE `db_logixla_crud` ;

-- -----------------------------------------------------
-- Table `db_logixla_crud`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_usuario` (
  `id` INT(255) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `clave` VARCHAR(200) NOT NULL,
  `admin` TINYINT NOT NULL DEFAULT 0,
  `habilitado` TINYINT NOT NULL DEFAULT 1,
  `eliminado` TINYINT NOT NULL DEFAULT 0,
  `fecha_creado` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_eliminado` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC));


-- -----------------------------------------------------
-- Table `db_logixla_crud`.`tb_articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_articulo` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `id_usuario_creador` INT(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `codigo_barra` VARCHAR(200) NOT NULL,
  `precio` DOUBLE NOT NULL DEFAULT 0,
  `marca` VARCHAR(100) NULL,
  `cantidad` INT(255) NOT NULL DEFAULT 0,
  `eliminado` TINYINT NOT NULL DEFAULT 0,
  `fecha_creado` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_eliminado` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo_barra_UNIQUE` (`codigo_barra` ASC),
  INDEX `fk_articulo_usuario_creador_idx` (`id_usuario_creador` ASC),
  CONSTRAINT `fk_articulo_usuario_creador`
    FOREIGN KEY (`id_usuario_creador`)
    REFERENCES `db_logixla_crud`.`tb_usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
